name: Build EasyReader Release

on:

  workflow_dispatch:

  push:
    tags:
      - "v*"


permissions:
  contents: write


jobs:

  build:

    runs-on: windows-latest


    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"


    - name: Install dependencies
      shell: cmd
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Download Piper model
      shell: cmd
      run: |
        python models\download_model.py


    - name: Build EXE
      shell: cmd
      run: |
        pyinstaller ^
        --clean ^
        --noconfirm ^
        EasyReader.spec


    - name: Prepare release folder
      shell: cmd
      run: |

        mkdir release

        xcopy dist\EasyReader release\EasyReader /E /I

        xcopy models release\EasyReader\models /E /I


    - name: Create ZIP
      shell: powershell
      run: |

        Compress-Archive `
        -Path release\EasyReader `
        -DestinationPath EasyReader-V1.0-Windows-x64.zip


    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:

        name: EasyReader-V1.0-Windows-x64

        path:
          EasyReader-V1.0-Windows-x64.zip



    - name: Create GitHub Release

      if: startsWith(github.ref,'refs/tags/')

      uses: softprops/action-gh-release@v2

      with:

        files:

          EasyReader-V1.0-Windows-x64.zip

        generate_release_notes: true
